# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm',
                'doc_host': 'https://mosessoh.github.io',
                'git_url': 'https://github.com/mosessoh/llm',
                'lib_path': 'llm'},
  'syms': {'llm.core': {'llm.core.foo': ('core.html#foo', 'llm/core.py')}}}
